name: job_me
description: A new Flutter project.
publish_to: 'none'

version: 1.0.9+10

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get: ^4.6.1
  flutter_svg: ^1.1.6
  shared_preferences: ^2.0.11
  encrypt: 5.0.1
  webview_flutter: ^4.0.2
  cupertino_icons: ^1.0.2
  uuid: ^3.0.7
  dio: ^4.0.6
  path: ^1.8.2
  path_provider: ^2.0.11
  pretty_dio_logger: ^1.1.1
  http: ^0.13.5
  internet_connection_checker_plus: ^1.0.1
  http_parser: ^4.0.2
  provider: ^6.0.5
  shimmer: 2.0.0
  intl:
  cached_network_image:
  pin_code_fields: ^7.0.0
  file_picker: ^5.2.3
  google_sign_in: ^5.4.3
  flutter_facebook_auth: ^3.5.7
  country_list_picker: ^1.0.1
  firebase_auth: ^4.1.4
  firebase_core: ^2.3.0
  carousel_slider: ^4.1.1
  photo_view:
  pusher_channels_flutter: ^2.1.2
  country_code_picker_x: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.11.0"

  flutter_lints: ^2.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/launcher_icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lang/
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cairo-Regular.ttf
          weight: 400
        - asset: assets/fonts/Cairo-Light.ttf
          weight: 300
